name: Buffer Auto Post

on:
  schedule:
    - cron: "0 15 * * *"   # UTCで毎日15:00 → 日本時間で毎日0:00
  workflow_dispatch:       # 手動実行ボタンを有効化

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth playwright
          playwright install chromium

      - name: Run Buffer Scheduler
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > creds.json
          python buffer_scheduler.py
